export const flights = [
  {
    airport: "SFO",
    gate: "Gate 01",
    date: "07/14/2020",
    turns: "1",
    category: "Pre-Arrival",
    time: "09:00:17",
    task: "Crew present 10 minutes prior to aircraft arrival",
    pass: true,
    video: "32s",
  },
  {
    airport: "SFO",
    gate: "Gate 01",
    date: "07/14/2020",
    turns: "1",
    category: "Pre-Arrival",
    time: "09:00:17",
    task: "Crew present 10 minutes prior to aircraft arrival",
    pass: false,
    video: "32s",
  },
  {
    airport: "SFO",
    gate: "Gate 01",
    date: "07/14/2020",
    turns: "1",
    category: "Pre-Arrival",
    time: "09:00:17",
    task: "Crew present 10 minutes prior to aircraft arrival",
    pass: true,
    video: "1m 15s",
  },
  {
    airport: "SFO",
    gate: "Gate 01",
    date: "07/14/2020",
    turns: "1",
    category: "Pre-Arrival",
    time: "09:00:17",
    task: "Crew present 10 minutes prior to aircraft arrival",
    pass: true,
    video: "32s",
  },
  {
    airport: "SFO",
    gate: "Gate 01",
    date: "07/14/2020",
    turns: "1",
    category: "Pre-Arrival",
    time: "09:00:17",
    task: "Crew present 10 minutes prior to aircraft arrival",
    pass: true,
    video: "32s",
  },
  {
    airport: "SFO",
    gate: "Gate 01",
    date: "07/14/2020",
    turns: "1",
    category: "Pre-Arrival",
    time: "09:00:17",
    task: "Safety cones in correct places and timely",
    pass: false,
    video: "08s",
  },
  {
    airport: "SFO",
    gate: "Gate 01",
    date: "07/14/2020",
    turns: "1",
    category: "Pre-Arrival",
    time: "09:00:17",
    task: "Safety cones in correct places and timely",
    pass: false,
    video: "32s",
  },
  {
    airport: "SFO",
    gate: "Gate 01",
    date: "07/14/2020",
    turns: "1",
    category: "Pre-Arrival",
    time: "09:00:17",
    task: "Safety cones in correct places and timely",
    pass: false,
    video: "2m 5s",
  },
  {
    airport: "SFO",
    gate: "Gate 01",
    date: "07/14/2020",
    turns: "1",
    category: "Pre-Arrival",
    time: "09:00:17",
    task: "Safety cones in correct places and timely",
    pass: true,
    video: "32s",
  },
  {
    airport: "SFO",
    gate: "Gate 01",
    date: "07/14/2020",
    turns: "1",
    category: "Pre-Arrival",
    time: "09:00:17",
    task: "Wing walkers and marshals in place and timely",
    pass: true,
    video: "32s",
  },
  {
    airport: "SFO",
    gate: "Gate 01",
    date: "07/14/2020",
    turns: "1",
    category: "Pre-Arrival",
    time: "09:00:17",
    task: "Wing walkers and marshals in place and timely",
    pass: false,
    video: "32s",
  },
];
